version: "3.2"

services:

  server:
    build: .
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - SERVER_PORT=${SERVER_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
    expose:
      - ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    links:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    expose:
      - ${MONGO_PORT}
    ports:
      - ${MONGO_PORT}:27017

volumes:
  mongo-data:
